### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by chubshaun** [lannonbr/repo-permission-check-action#10]
@lannonbr I can't seem to get this to work:

```yaml
steps:
  - name: "Check if user has write access"
    uses: "lannonbr/repo-permission-check-action@2.0.0"
    with:
      permission: "admin"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  - name: "next Step"
  ...
```

No matter what happens in permission-check-action it seems to go directly to the next step. Shouldn't this fail the build? I even tried a obviously fake permission and it still succeeded with `permission: "fake_permission"`.
