### ISSUE TITLE
Doesn't work with workflow_dispatch ?

### ISSUE THREAD

**Issue by skjnldsv** [lannonbr/repo-permission-check-action#7]
Hi @lannonbr, it doesn't seems to work with workflow_dispatch ?
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch

I recently tested it and the full workflow started.
Do I need to have a `if` somewhere to rely on yours passing?

Have a nice day :sun_with_face: 

_____
See my example

```yml
name: Update workflow from org template

on:
  workflow_dispatch:
    inputs:
      name:
        description: "The workflow to update (with .yml)"
        required: true
        default: "node.yml"

jobs:
  repositories:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.search-repos.outputs.matrix }}

    steps:
      - name: Check if user has write access
        uses: lannonbr/repo-permission-check-action@2.0.0
        with:
          permission: admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Step
        run: # .... various steps

  dispatch:
    runs-on: ubuntu-latest
    needs: repositories
    strategy:
      matrix:
        repositories: ${{ fromJSON(needs.repositories.outputs.matrix) }}

    steps:
      - name: Step
        run: # .... various steps

```
